// Code generated by https://github.com/lynxai-team/emo/blob/main/codegen/golang/gen.go ; DO NOT EDIT.

package emo

import "fmt"

func AccessToken(args ...any) Event {
	return DefaultZone.NewEvent("🔑", true, args...).Print().CallHook()
}

func AccessTokenf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔑", true, s).Print().CallHook()
}

func (zone Zone) AccessToken(args ...any) Event {
	return zone.NewEvent("🔑", true, args...).Print().CallHook()
}

func (zone Zone) AccessTokenf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔑", true, s).Print().CallHook()
}

func Aconstructor(args ...any) Event {
	return DefaultZone.NewEvent("🛠️", true, args...).Print().CallHook()
}

func Aconstructorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🛠️", true, s).Print().CallHook()
}

func (zone Zone) Aconstructor(args ...any) Event {
	return zone.NewEvent("🛠️", true, args...).Print().CallHook()
}

func (zone Zone) Aconstructorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🛠️", true, s).Print().CallHook()
}

func AconstructorError(args ...any) Event {
	return DefaultZone.NewEvent("🛠️", true, args...).Print().CallHook()
}

func AconstructorErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🛠️", true, s).Print().CallHook()
}

func (zone Zone) AconstructorError(args ...any) Event {
	return zone.NewEvent("🛠️", true, args...).Print().CallHook()
}

func (zone Zone) AconstructorErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🛠️", true, s).Print().CallHook()
}

func ArrowIn(args ...any) Event {
	return DefaultZone.NewEvent("=>", true, args...).Print().CallHook()
}

func ArrowInf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("=>", true, s).Print().CallHook()
}

func (zone Zone) ArrowIn(args ...any) Event {
	return zone.NewEvent("=>", true, args...).Print().CallHook()
}

func (zone Zone) ArrowInf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("=>", true, s).Print().CallHook()
}

func ArrowInError(args ...any) Event {
	return DefaultZone.NewEvent("=>", true, args...).Print().CallHook()
}

func ArrowInErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("=>", true, s).Print().CallHook()
}

func (zone Zone) ArrowInError(args ...any) Event {
	return zone.NewEvent("=>", true, args...).Print().CallHook()
}

func (zone Zone) ArrowInErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("=>", true, s).Print().CallHook()
}

func ArrowOut(args ...any) Event {
	return DefaultZone.NewEvent("<=", true, args...).Print().CallHook()
}

func ArrowOutf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("<=", true, s).Print().CallHook()
}

func (zone Zone) ArrowOut(args ...any) Event {
	return zone.NewEvent("<=", true, args...).Print().CallHook()
}

func (zone Zone) ArrowOutf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("<=", true, s).Print().CallHook()
}

func ArrowOutError(args ...any) Event {
	return DefaultZone.NewEvent("<=", true, args...).Print().CallHook()
}

func ArrowOutErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("<=", true, s).Print().CallHook()
}

func (zone Zone) ArrowOutError(args ...any) Event {
	return zone.NewEvent("<=", true, args...).Print().CallHook()
}

func (zone Zone) ArrowOutErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("<=", true, s).Print().CallHook()
}

func Build(args ...any) Event {
	return DefaultZone.NewEvent("🔧", true, args...).Print().CallHook()
}

func Buildf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔧", true, s).Print().CallHook()
}

func (zone Zone) Build(args ...any) Event {
	return zone.NewEvent("🔧", true, args...).Print().CallHook()
}

func (zone Zone) Buildf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔧", true, s).Print().CallHook()
}

func BuildError(args ...any) Event {
	return DefaultZone.NewEvent("🔧", true, args...).Print().CallHook()
}

func BuildErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔧", true, s).Print().CallHook()
}

func (zone Zone) BuildError(args ...any) Event {
	return zone.NewEvent("🔧", true, args...).Print().CallHook()
}

func (zone Zone) BuildErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔧", true, s).Print().CallHook()
}

func Data(args ...any) Event {
	return DefaultZone.NewEvent("💼", true, args...).Print().CallHook()
}

func Dataf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("💼", true, s).Print().CallHook()
}

func (zone Zone) Data(args ...any) Event {
	return zone.NewEvent("💼", true, args...).Print().CallHook()
}

func (zone Zone) Dataf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("💼", true, s).Print().CallHook()
}

func DataError(args ...any) Event {
	return DefaultZone.NewEvent("💼", true, args...).Print().CallHook()
}

func DataErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("💼", true, s).Print().CallHook()
}

func (zone Zone) DataError(args ...any) Event {
	return zone.NewEvent("💼", true, args...).Print().CallHook()
}

func (zone Zone) DataErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("💼", true, s).Print().CallHook()
}

func Debug(args ...any) Event {
	return DefaultZone.NewEvent("💊", true, args...).Print().CallHook()
}

func Debugf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("💊", true, s).Print().CallHook()
}

func (zone Zone) Debug(args ...any) Event {
	return zone.NewEvent("💊", true, args...).Print().CallHook()
}

func (zone Zone) Debugf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("💊", true, s).Print().CallHook()
}

func Decrypt(args ...any) Event {
	return DefaultZone.NewEvent("🗝️", true, args...).Print().CallHook()
}

func Decryptf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🗝️", true, s).Print().CallHook()
}

func (zone Zone) Decrypt(args ...any) Event {
	return zone.NewEvent("🗝️", true, args...).Print().CallHook()
}

func (zone Zone) Decryptf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🗝️", true, s).Print().CallHook()
}

func DecryptError(args ...any) Event {
	return DefaultZone.NewEvent("🗝️", true, args...).Print().CallHook()
}

func DecryptErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🗝️", true, s).Print().CallHook()
}

func (zone Zone) DecryptError(args ...any) Event {
	return zone.NewEvent("🗝️", true, args...).Print().CallHook()
}

func (zone Zone) DecryptErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🗝️", true, s).Print().CallHook()
}

func Delete(args ...any) Event {
	return DefaultZone.NewEvent("❌", true, args...).Print().CallHook()
}

func Deletef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("❌", true, s).Print().CallHook()
}

func (zone Zone) Delete(args ...any) Event {
	return zone.NewEvent("❌", true, args...).Print().CallHook()
}

func (zone Zone) Deletef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("❌", true, s).Print().CallHook()
}

func DeleteError(args ...any) Event {
	return DefaultZone.NewEvent("❌", true, args...).Print().CallHook()
}

func DeleteErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("❌", true, s).Print().CallHook()
}

func (zone Zone) DeleteError(args ...any) Event {
	return zone.NewEvent("❌", true, args...).Print().CallHook()
}

func (zone Zone) DeleteErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("❌", true, s).Print().CallHook()
}

func Encrypt(args ...any) Event {
	return DefaultZone.NewEvent("🎼", true, args...).Print().CallHook()
}

func Encryptf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🎼", true, s).Print().CallHook()
}

func (zone Zone) Encrypt(args ...any) Event {
	return zone.NewEvent("🎼", true, args...).Print().CallHook()
}

func (zone Zone) Encryptf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🎼", true, s).Print().CallHook()
}

func EncryptError(args ...any) Event {
	return DefaultZone.NewEvent("🎼", true, args...).Print().CallHook()
}

func EncryptErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🎼", true, s).Print().CallHook()
}

func (zone Zone) EncryptError(args ...any) Event {
	return zone.NewEvent("🎼", true, args...).Print().CallHook()
}

func (zone Zone) EncryptErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🎼", true, s).Print().CallHook()
}

func Error(args ...any) Event {
	return DefaultZone.NewEvent("💢", true, args...).Print().CallHook()
}

func Errorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("💢", true, s).Print().CallHook()
}

func (zone Zone) Error(args ...any) Event {
	return zone.NewEvent("💢", true, args...).Print().CallHook()
}

func (zone Zone) Errorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("💢", true, s).Print().CallHook()
}

func Found(args ...any) Event {
	return DefaultZone.NewEvent("👁️‍🗨️", true, args...).Print().CallHook()
}

func Foundf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("👁️‍🗨️", true, s).Print().CallHook()
}

func (zone Zone) Found(args ...any) Event {
	return zone.NewEvent("👁️‍🗨️", true, args...).Print().CallHook()
}

func (zone Zone) Foundf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("👁️‍🗨️", true, s).Print().CallHook()
}

func Function(args ...any) Event {
	return DefaultZone.NewEvent("🔨", true, args...).Print().CallHook()
}

func Functionf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔨", true, s).Print().CallHook()
}

func (zone Zone) Function(args ...any) Event {
	return zone.NewEvent("🔨", true, args...).Print().CallHook()
}

func (zone Zone) Functionf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔨", true, s).Print().CallHook()
}

func FunctionError(args ...any) Event {
	return DefaultZone.NewEvent("🔨", true, args...).Print().CallHook()
}

func FunctionErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔨", true, s).Print().CallHook()
}

func (zone Zone) FunctionError(args ...any) Event {
	return zone.NewEvent("🔨", true, args...).Print().CallHook()
}

func (zone Zone) FunctionErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔨", true, s).Print().CallHook()
}

func In(args ...any) Event {
	return DefaultZone.NewEvent("→", true, args...).Print().CallHook()
}

func Inf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("→", true, s).Print().CallHook()
}

func (zone Zone) In(args ...any) Event {
	return zone.NewEvent("→", true, args...).Print().CallHook()
}

func (zone Zone) Inf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("→", true, s).Print().CallHook()
}

func InError(args ...any) Event {
	return DefaultZone.NewEvent("→", true, args...).Print().CallHook()
}

func InErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("→", true, s).Print().CallHook()
}

func (zone Zone) InError(args ...any) Event {
	return zone.NewEvent("→", true, args...).Print().CallHook()
}

func (zone Zone) InErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("→", true, s).Print().CallHook()
}

func Info(args ...any) Event {
	return DefaultZone.NewEvent("ℹ️", true, args...).Print().CallHook()
}

func Infof(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("ℹ️", true, s).Print().CallHook()
}

func (zone Zone) Info(args ...any) Event {
	return zone.NewEvent("ℹ️", true, args...).Print().CallHook()
}

func (zone Zone) Infof(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("ℹ️", true, s).Print().CallHook()
}

func Init(args ...any) Event {
	return DefaultZone.NewEvent("🎬", true, args...).Print().CallHook()
}

func Initf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🎬", true, s).Print().CallHook()
}

func (zone Zone) Init(args ...any) Event {
	return zone.NewEvent("🎬", true, args...).Print().CallHook()
}

func (zone Zone) Initf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🎬", true, s).Print().CallHook()
}

func InitError(args ...any) Event {
	return DefaultZone.NewEvent("🎬", true, args...).Print().CallHook()
}

func InitErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🎬", true, s).Print().CallHook()
}

func (zone Zone) InitError(args ...any) Event {
	return zone.NewEvent("🎬", true, args...).Print().CallHook()
}

func (zone Zone) InitErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🎬", true, s).Print().CallHook()
}

func Input(args ...any) Event {
	return DefaultZone.NewEvent("📥", true, args...).Print().CallHook()
}

func Inputf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📥", true, s).Print().CallHook()
}

func (zone Zone) Input(args ...any) Event {
	return zone.NewEvent("📥", true, args...).Print().CallHook()
}

func (zone Zone) Inputf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📥", true, s).Print().CallHook()
}

func InputError(args ...any) Event {
	return DefaultZone.NewEvent("📥", true, args...).Print().CallHook()
}

func InputErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📥", true, s).Print().CallHook()
}

func (zone Zone) InputError(args ...any) Event {
	return zone.NewEvent("📥", true, args...).Print().CallHook()
}

func (zone Zone) InputErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📥", true, s).Print().CallHook()
}

func Key(args ...any) Event {
	return DefaultZone.NewEvent("🔑", true, args...).Print().CallHook()
}

func Keyf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔑", true, s).Print().CallHook()
}

func (zone Zone) Key(args ...any) Event {
	return zone.NewEvent("🔑", true, args...).Print().CallHook()
}

func (zone Zone) Keyf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔑", true, s).Print().CallHook()
}

func KeyError(args ...any) Event {
	return DefaultZone.NewEvent("🔑", true, args...).Print().CallHook()
}

func KeyErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔑", true, s).Print().CallHook()
}

func (zone Zone) KeyError(args ...any) Event {
	return zone.NewEvent("🔑", true, args...).Print().CallHook()
}

func (zone Zone) KeyErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔑", true, s).Print().CallHook()
}

func Line(args ...any) Event {
	return DefaultZone.NewEvent("➖", true, args...).Print().CallHook()
}

func Linef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("➖", true, s).Print().CallHook()
}

func (zone Zone) Line(args ...any) Event {
	return zone.NewEvent("➖", true, args...).Print().CallHook()
}

func (zone Zone) Linef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("➖", true, s).Print().CallHook()
}

func LineError(args ...any) Event {
	return DefaultZone.NewEvent("➖", true, args...).Print().CallHook()
}

func LineErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("➖", true, s).Print().CallHook()
}

func (zone Zone) LineError(args ...any) Event {
	return zone.NewEvent("➖", true, args...).Print().CallHook()
}

func (zone Zone) LineErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("➖", true, s).Print().CallHook()
}

func NotFound(args ...any) Event {
	return DefaultZone.NewEvent("🚫", true, args...).Print().CallHook()
}

func NotFoundf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🚫", true, s).Print().CallHook()
}

func (zone Zone) NotFound(args ...any) Event {
	return zone.NewEvent("🚫", true, args...).Print().CallHook()
}

func (zone Zone) NotFoundf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🚫", true, s).Print().CallHook()
}

func Ok(args ...any) Event {
	return DefaultZone.NewEvent("🆗", true, args...).Print().CallHook()
}

func Okf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🆗", true, s).Print().CallHook()
}

func (zone Zone) Ok(args ...any) Event {
	return zone.NewEvent("🆗", true, args...).Print().CallHook()
}

func (zone Zone) Okf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🆗", true, s).Print().CallHook()
}

func Out(args ...any) Event {
	return DefaultZone.NewEvent("←", true, args...).Print().CallHook()
}

func Outf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("←", true, s).Print().CallHook()
}

func (zone Zone) Out(args ...any) Event {
	return zone.NewEvent("←", true, args...).Print().CallHook()
}

func (zone Zone) Outf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("←", true, s).Print().CallHook()
}

func OutError(args ...any) Event {
	return DefaultZone.NewEvent("←", true, args...).Print().CallHook()
}

func OutErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("←", true, s).Print().CallHook()
}

func (zone Zone) OutError(args ...any) Event {
	return zone.NewEvent("←", true, args...).Print().CallHook()
}

func (zone Zone) OutErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("←", true, s).Print().CallHook()
}

func Output(args ...any) Event {
	return DefaultZone.NewEvent("📤", true, args...).Print().CallHook()
}

func Outputf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📤", true, s).Print().CallHook()
}

func (zone Zone) Output(args ...any) Event {
	return zone.NewEvent("📤", true, args...).Print().CallHook()
}

func (zone Zone) Outputf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📤", true, s).Print().CallHook()
}

func OutputError(args ...any) Event {
	return DefaultZone.NewEvent("📤", true, args...).Print().CallHook()
}

func OutputErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📤", true, s).Print().CallHook()
}

func (zone Zone) OutputError(args ...any) Event {
	return zone.NewEvent("📤", true, args...).Print().CallHook()
}

func (zone Zone) OutputErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📤", true, s).Print().CallHook()
}

func Param(args ...any) Event {
	return DefaultZone.NewEvent("📩", true, args...).Print().CallHook()
}

func Paramf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📩", true, s).Print().CallHook()
}

func (zone Zone) Param(args ...any) Event {
	return zone.NewEvent("📩", true, args...).Print().CallHook()
}

func (zone Zone) Paramf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📩", true, s).Print().CallHook()
}

func ParamError(args ...any) Event {
	return DefaultZone.NewEvent("📩", true, args...).Print().CallHook()
}

func ParamErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📩", true, s).Print().CallHook()
}

func (zone Zone) ParamError(args ...any) Event {
	return zone.NewEvent("📩", true, args...).Print().CallHook()
}

func (zone Zone) ParamErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📩", true, s).Print().CallHook()
}

func Query(args ...any) Event {
	return DefaultZone.NewEvent("🗄️", true, args...).Print().CallHook()
}

func Queryf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🗄️", true, s).Print().CallHook()
}

func (zone Zone) Query(args ...any) Event {
	return zone.NewEvent("🗄️", true, args...).Print().CallHook()
}

func (zone Zone) Queryf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🗄️", true, s).Print().CallHook()
}

func QueryError(args ...any) Event {
	return DefaultZone.NewEvent("🗄️", true, args...).Print().CallHook()
}

func QueryErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🗄️", true, s).Print().CallHook()
}

func (zone Zone) QueryError(args ...any) Event {
	return zone.NewEvent("🗄️", true, args...).Print().CallHook()
}

func (zone Zone) QueryErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🗄️", true, s).Print().CallHook()
}

func RefreshToken(args ...any) Event {
	return DefaultZone.NewEvent("🗝️", true, args...).Print().CallHook()
}

func RefreshTokenf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🗝️", true, s).Print().CallHook()
}

func (zone Zone) RefreshToken(args ...any) Event {
	return zone.NewEvent("🗝️", true, args...).Print().CallHook()
}

func (zone Zone) RefreshTokenf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🗝️", true, s).Print().CallHook()
}

func RequestGet(args ...any) Event {
	return DefaultZone.NewEvent("🔷", true, args...).Print().CallHook()
}

func RequestGetf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔷", true, s).Print().CallHook()
}

func (zone Zone) RequestGet(args ...any) Event {
	return zone.NewEvent("🔷", true, args...).Print().CallHook()
}

func (zone Zone) RequestGetf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔷", true, s).Print().CallHook()
}

func RequestGetError(args ...any) Event {
	return DefaultZone.NewEvent("🔷", true, args...).Print().CallHook()
}

func RequestGetErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔷", true, s).Print().CallHook()
}

func (zone Zone) RequestGetError(args ...any) Event {
	return zone.NewEvent("🔷", true, args...).Print().CallHook()
}

func (zone Zone) RequestGetErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔷", true, s).Print().CallHook()
}

func RequestPost(args ...any) Event {
	return DefaultZone.NewEvent("🔶", true, args...).Print().CallHook()
}

func RequestPostf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔶", true, s).Print().CallHook()
}

func (zone Zone) RequestPost(args ...any) Event {
	return zone.NewEvent("🔶", true, args...).Print().CallHook()
}

func (zone Zone) RequestPostf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔶", true, s).Print().CallHook()
}

func RequestPostError(args ...any) Event {
	return DefaultZone.NewEvent("🔶", true, args...).Print().CallHook()
}

func RequestPostErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔶", true, s).Print().CallHook()
}

func (zone Zone) RequestPostError(args ...any) Event {
	return zone.NewEvent("🔶", true, args...).Print().CallHook()
}

func (zone Zone) RequestPostErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔶", true, s).Print().CallHook()
}

func Result(args ...any) Event {
	return DefaultZone.NewEvent("📌", true, args...).Print().CallHook()
}

func Resultf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📌", true, s).Print().CallHook()
}

func (zone Zone) Result(args ...any) Event {
	return zone.NewEvent("📌", true, args...).Print().CallHook()
}

func (zone Zone) Resultf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📌", true, s).Print().CallHook()
}

func ResultError(args ...any) Event {
	return DefaultZone.NewEvent("📌", true, args...).Print().CallHook()
}

func ResultErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📌", true, s).Print().CallHook()
}

func (zone Zone) ResultError(args ...any) Event {
	return zone.NewEvent("📌", true, args...).Print().CallHook()
}

func (zone Zone) ResultErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📌", true, s).Print().CallHook()
}

func Save(args ...any) Event {
	return DefaultZone.NewEvent("💾", true, args...).Print().CallHook()
}

func Savef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("💾", true, s).Print().CallHook()
}

func (zone Zone) Save(args ...any) Event {
	return zone.NewEvent("💾", true, args...).Print().CallHook()
}

func (zone Zone) Savef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("💾", true, s).Print().CallHook()
}

func SaveError(args ...any) Event {
	return DefaultZone.NewEvent("💾", true, args...).Print().CallHook()
}

func SaveErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("💾", true, s).Print().CallHook()
}

func (zone Zone) SaveError(args ...any) Event {
	return zone.NewEvent("💾", true, args...).Print().CallHook()
}

func (zone Zone) SaveErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("💾", true, s).Print().CallHook()
}

func Security(args ...any) Event {
	return DefaultZone.NewEvent("🔒", true, args...).Print().CallHook()
}

func Securityf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔒", true, s).Print().CallHook()
}

func (zone Zone) Security(args ...any) Event {
	return zone.NewEvent("🔒", true, args...).Print().CallHook()
}

func (zone Zone) Securityf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔒", true, s).Print().CallHook()
}

func SecurityError(args ...any) Event {
	return DefaultZone.NewEvent("🔒", true, args...).Print().CallHook()
}

func SecurityErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔒", true, s).Print().CallHook()
}

func (zone Zone) SecurityError(args ...any) Event {
	return zone.NewEvent("🔒", true, args...).Print().CallHook()
}

func (zone Zone) SecurityErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔒", true, s).Print().CallHook()
}

func SmallArrowIn(args ...any) Event {
	return DefaultZone.NewEvent("->", true, args...).Print().CallHook()
}

func SmallArrowInf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("->", true, s).Print().CallHook()
}

func (zone Zone) SmallArrowIn(args ...any) Event {
	return zone.NewEvent("->", true, args...).Print().CallHook()
}

func (zone Zone) SmallArrowInf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("->", true, s).Print().CallHook()
}

func SmallArrowInError(args ...any) Event {
	return DefaultZone.NewEvent("->", true, args...).Print().CallHook()
}

func SmallArrowInErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("->", true, s).Print().CallHook()
}

func (zone Zone) SmallArrowInError(args ...any) Event {
	return zone.NewEvent("->", true, args...).Print().CallHook()
}

func (zone Zone) SmallArrowInErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("->", true, s).Print().CallHook()
}

func SmallArrowOut(args ...any) Event {
	return DefaultZone.NewEvent("<-", true, args...).Print().CallHook()
}

func SmallArrowOutf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("<-", true, s).Print().CallHook()
}

func (zone Zone) SmallArrowOut(args ...any) Event {
	return zone.NewEvent("<-", true, args...).Print().CallHook()
}

func (zone Zone) SmallArrowOutf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("<-", true, s).Print().CallHook()
}

func SmallArrowOutError(args ...any) Event {
	return DefaultZone.NewEvent("<-", true, args...).Print().CallHook()
}

func SmallArrowOutErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("<-", true, s).Print().CallHook()
}

func (zone Zone) SmallArrowOutError(args ...any) Event {
	return zone.NewEvent("<-", true, args...).Print().CallHook()
}

func (zone Zone) SmallArrowOutErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("<-", true, s).Print().CallHook()
}

func Start(args ...any) Event {
	return DefaultZone.NewEvent("🏁", true, args...).Print().CallHook()
}

func Startf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🏁", true, s).Print().CallHook()
}

func (zone Zone) Start(args ...any) Event {
	return zone.NewEvent("🏁", true, args...).Print().CallHook()
}

func (zone Zone) Startf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🏁", true, s).Print().CallHook()
}

func StartError(args ...any) Event {
	return DefaultZone.NewEvent("🏁", true, args...).Print().CallHook()
}

func StartErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🏁", true, s).Print().CallHook()
}

func (zone Zone) StartError(args ...any) Event {
	return zone.NewEvent("🏁", true, args...).Print().CallHook()
}

func (zone Zone) StartErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🏁", true, s).Print().CallHook()
}

func State(args ...any) Event {
	return DefaultZone.NewEvent("📢", true, args...).Print().CallHook()
}

func Statef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📢", true, s).Print().CallHook()
}

func (zone Zone) State(args ...any) Event {
	return zone.NewEvent("📢", true, args...).Print().CallHook()
}

func (zone Zone) Statef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📢", true, s).Print().CallHook()
}

func StateError(args ...any) Event {
	return DefaultZone.NewEvent("📢", true, args...).Print().CallHook()
}

func StateErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📢", true, s).Print().CallHook()
}

func (zone Zone) StateError(args ...any) Event {
	return zone.NewEvent("📢", true, args...).Print().CallHook()
}

func (zone Zone) StateErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📢", true, s).Print().CallHook()
}

func Stop(args ...any) Event {
	return DefaultZone.NewEvent("🛑", true, args...).Print().CallHook()
}

func Stopf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🛑", true, s).Print().CallHook()
}

func (zone Zone) Stop(args ...any) Event {
	return zone.NewEvent("🛑", true, args...).Print().CallHook()
}

func (zone Zone) Stopf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🛑", true, s).Print().CallHook()
}

func StopError(args ...any) Event {
	return DefaultZone.NewEvent("🛑", true, args...).Print().CallHook()
}

func StopErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🛑", true, s).Print().CallHook()
}

func (zone Zone) StopError(args ...any) Event {
	return zone.NewEvent("🛑", true, args...).Print().CallHook()
}

func (zone Zone) StopErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🛑", true, s).Print().CallHook()
}

func Time(args ...any) Event {
	return DefaultZone.NewEvent("⏱️", true, args...).Print().CallHook()
}

func Timef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("⏱️", true, s).Print().CallHook()
}

func (zone Zone) Time(args ...any) Event {
	return zone.NewEvent("⏱️", true, args...).Print().CallHook()
}

func (zone Zone) Timef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("⏱️", true, s).Print().CallHook()
}

func TimeError(args ...any) Event {
	return DefaultZone.NewEvent("⏱️", true, args...).Print().CallHook()
}

func TimeErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("⏱️", true, s).Print().CallHook()
}

func (zone Zone) TimeError(args ...any) Event {
	return zone.NewEvent("⏱️", true, args...).Print().CallHook()
}

func (zone Zone) TimeErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("⏱️", true, s).Print().CallHook()
}

func Transmit(args ...any) Event {
	return DefaultZone.NewEvent("📡", true, args...).Print().CallHook()
}

func Transmitf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📡", true, s).Print().CallHook()
}

func (zone Zone) Transmit(args ...any) Event {
	return zone.NewEvent("📡", true, args...).Print().CallHook()
}

func (zone Zone) Transmitf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📡", true, s).Print().CallHook()
}

func TransmitError(args ...any) Event {
	return DefaultZone.NewEvent("📡", true, args...).Print().CallHook()
}

func TransmitErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("📡", true, s).Print().CallHook()
}

func (zone Zone) TransmitError(args ...any) Event {
	return zone.NewEvent("📡", true, args...).Print().CallHook()
}

func (zone Zone) TransmitErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("📡", true, s).Print().CallHook()
}

func Update(args ...any) Event {
	return DefaultZone.NewEvent("🆙", true, args...).Print().CallHook()
}

func Updatef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🆙", true, s).Print().CallHook()
}

func (zone Zone) Update(args ...any) Event {
	return zone.NewEvent("🆙", true, args...).Print().CallHook()
}

func (zone Zone) Updatef(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🆙", true, s).Print().CallHook()
}

func UpdateError(args ...any) Event {
	return DefaultZone.NewEvent("🆙", true, args...).Print().CallHook()
}

func UpdateErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🆙", true, s).Print().CallHook()
}

func (zone Zone) UpdateError(args ...any) Event {
	return zone.NewEvent("🆙", true, args...).Print().CallHook()
}

func (zone Zone) UpdateErrorf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🆙", true, s).Print().CallHook()
}

func Warning(args ...any) Event {
	return DefaultZone.NewEvent("🔔", true, args...).Print().CallHook()
}

func Warningf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("🔔", true, s).Print().CallHook()
}

func (zone Zone) Warning(args ...any) Event {
	return zone.NewEvent("🔔", true, args...).Print().CallHook()
}

func (zone Zone) Warningf(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("🔔", true, s).Print().CallHook()
}
