package golang

import (
	"fmt"
	"log"
	"path/filepath"
	"strings"

	"github.com/lynxai-team/emo/codegen/core"

	"github.com/dolmen-go/codegen"
)

func GenGo(ref []core.Ref) {
	var template strings.Builder
	template.WriteString(fileStart)
	for _, item := range ref {
		var functions string
		if item.IsError {
			functions = genErrorFunctions(item.Name, item.Emoji)
		} else {
			functions = genOtherFunctions(item.Name, item.Emoji)
		}
		template.WriteString(functions)
	}

	tmpl := codegen.MustParse(template.String())

	fn, err := filepath.Abs("generated.go")
	if err != nil {
		log.Fatal(err)
	}

	if err := tmpl.CreateFile(fn, "emo"); err != nil {
		log.Fatal(err)
	}

	fmt.Println("[codegen] File: " + fn)
}

var fileStart = `// Code generated by https://github.com/lynxai-team/emo/blob/main/codegen/golang/gen.go ; DO NOT EDIT.

package emo

import "fmt"
`

func genErrorFunctions(name, emoji string) string {
	return `

func ` + name + `(args ...any) Event {
	return DefaultZone.NewEvent("` + emoji + `", true, args...).Print().CallHook()
}

func ` + name + `f(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("` + emoji + `", true, s).Print().CallHook()
}

func (zone Zone) ` + name + `(args ...any) Event {
	return zone.NewEvent("` + emoji + `", true, args...).Print().CallHook()
}

func (zone Zone) ` + name + `f(format string, v ...any) Event {
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("` + emoji + `", true, s).Print().CallHook()
}

`
}

func genOtherFunctions(name, emoji string) string {
	return `

func ` + name + `(args ...any) Event {
	if !DefaultZone.enabled(false) {
		var evt Event
		return evt
	}
	return DefaultZone.NewEvent("` + emoji + `", false, args...).Print().CallHook()
}

func ` + name + `f(format string, v ...any) Event {
	if !DefaultZone.enabled(false) {
		var evt Event
		return evt
	}
	s := fmt.Sprintf(format, v...)
	return DefaultZone.NewEvent("` + emoji + `", false, s).Print().CallHook()
}

func (zone Zone) ` + name + `(args ...any) Event {
	if !zone.enabled(false) {
		var evt Event
		return evt
	}
	return zone.NewEvent("` + emoji + `", false, args...).Print().CallHook()
}

func (zone Zone) ` + name + `f(format string, v ...any) Event {
	if !zone.enabled(false) {
		var evt Event
		return evt
	}
	s := fmt.Sprintf(format, v...)
	return zone.NewEvent("` + emoji + `", false, s).Print().CallHook()
}
`
}
